platform :ios, '12.0'

require_relative '../../node_modules/react-native/scripts/react_native_pods'
require_relative '../../node_modules/@react-native-community/cli-platform-ios/native_modules'

project './example.xcodeproj'

target 'example' do
  use_native_modules!

  pod 'react-native-webview', :path => "../.."

  use_react_native!(
    :path => "../../node_modules/react-native",
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'exampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

target 'example-tvOS' do
  # Pods for example-tvOS

  target 'example-tvOSTests' do
    inherit! :complete
    # Pods for testing
  end

end
